# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

swagger:
    title: FreightForge API
    description:
    version: 1.0.0
    termsOfServiceUrl:
    contact:
    license:
    licenseUrl:
